### ISSUE TITLE
Introduce variables for margin-top, margin-bottom and line-hight for p and h1-h6 

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/buckram#1]
In addition to the existing variables 
$hx-margin-top: 1.5em !default; 
$hx-margin-bottom: 1em !default; 
$hx-line-height: 1.5em !default; 

also introduce the corresponsing variables for p and h1-h6

**Comment by greatislander** [comment]
`$para-margin-bottom`, `$para-margin-top`, `$para-no-indent-margin-top` and `$body-line-height` cover this for paragraphs.

**Comment by greatislander** [comment]
Closed in #8.
