### ISSUE TITLE
EPUB chapter subtitle column span

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/buckram#108]
Chapter subtitles break chapter styling on chapters they are featured on. This is caused by style "column-span: all" on the element. When turned off, it fixes problem behaviour. 

First page with "column-span: all"
![screen shot 2018-05-08 at 12 01 49 pm](https://user-images.githubusercontent.com/21149722/39768583-bd5cd7d8-52b7-11e8-8218-65d7de2167fa.png)

Second page with "column-span: all"
![screen shot 2018-05-08 at 12 01 59 pm](https://user-images.githubusercontent.com/21149722/39768594-c42f8538-52b7-11e8-8d2b-0e62ccd2bf4c.png)

First page with "column-span: all" removed:
![screen shot 2018-05-08 at 12 02 10 pm](https://user-images.githubusercontent.com/21149722/39768623-de7f92c0-52b7-11e8-8fab-480615313dad.png)

Second page with "column-span: all" removed:
![screen shot 2018-05-08 at 12 02 20 pm](https://user-images.githubusercontent.com/21149722/39768642-efec19e8-52b7-11e8-97fc-b41177b02873.png)

**Comment by greatislander** [comment]
Fixed in #113.
