### ISSUE TITLE
'Pre' element margin top and bottom

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/buckram#109]
Html element 'pre' needs top and bottom margin added. Problem has happened in all new buckram themes. 

Old: 
![screen shot 2018-05-03 at 11 43 21 am](https://user-images.githubusercontent.com/21149722/39777671-2cecf14a-52d2-11e8-876b-d2b8a944d88b.png)

New:
![screen shot 2018-05-03 at 11 43 11 am](https://user-images.githubusercontent.com/21149722/39777721-513b41f0-52d2-11e8-840b-8dab7c08f7c5.png)

**Comment by greatislander** [comment]
@dannylonglegs Can you open a PR for this (start from most recent `dev` branch). The rule should be:

`p + pre { margin-top: <some-sensible-variable-name>; }`

**Comment by greatislander** [comment]
Fixed in #114.
