### ISSUE TITLE
images / aligned images have bad top margins

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/buckram#175]
**Images**
Left/right aligned NO caption images appear as expected, with top of image aligning with the top line of the para. (yay!)

However, left/right align images WITH CAPTIONs however, are aligned poorly, floating a full line-height above the image (boo!)

See below: 
Good! (aligned images, no captions): 
https://www.dropbox.com/s/je4zhmyt89vm1r8/aligned-imgs-no-caps.png?dl=0

Bad! (aligned images, with captions):
https://www.dropbox.com/s/m1326gf99tb0r26/aligned-img-w-cap-BAD.png?dl=0

**Comment by greatislander** [comment]
@hughmcguire I looked in the markup and there is an empty paragraph right after that image which is causing the weird margin. Not a Buckram bug :)
