### ISSUE TITLE
Tables with border width >1px do not display correctly

### ISSUE THREAD

**Issue by jcguan1** [pressbooks/buckram#221]
When borders have a width set at >1px, top and bottom border still display as 1px. 

This only seems to happen for certain buckram themes. though. (ex: Baker is OK)

![image](https://user-images.githubusercontent.com/37554869/46166475-49c40700-c261-11e8-8b26-75cff08a9174.png)

**Comment by dannylonglegs** [comment]
@greatislander Should this issue be closed due to the recent table changes?

**Comment by greatislander** [comment]
@dannylonglegs Please test again and see what happens.

**Comment by greatislander** [comment]
Yes— we no longer support the built-in border width property so this is no longer relevant.
