### ISSUE TITLE
Move components from pressbooks-book to this standalone repo

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/buckram#269]
Rather than continuing to maintain buckram and aetna as Lerna-managed monorepos inside of pressbooks-book, we're planning to move each of these back into their own, standalone repos. @greatislander will help.

**Comment by greatislander** [comment]
Resolved as of 8d43d55.

**Comment by greatislander** [comment]
@fdalcin @SteelWagstaff this is down now, I think.

**Comment by SteelWagstaff** [comment]
@greatislander Done? or _down_?

**Comment by greatislander** [comment]
Done!
