### ISSUE TITLE
Reconnect Netlify for docs

### ISSUE THREAD

**Issue by greatislander** [pressbooks/buckram#283]
I don't have sufficient permissions to update the repository that builds https://buckram.pressbooks.org to point to this repository instead of the `packages/buckram` directory of `pressbooks-book`.

**Comment by SteelWagstaff** [comment]
@greatislander I do -- how can I help with this?

**Comment by greatislander** [comment]
@SteelWagstaff go here: https://app.netlify.com/sites/buckram/settings/deploys

Change the repository to `pressbooks/buckram`:

<img width="929" alt="Screen Shot 2022-08-17 at 8 23 07 PM" src="https://user-images.githubusercontent.com/605361/185260470-fd3440c9-4251-4e6f-a7d7-cbdd7f23dbaa.png">

Then change the "Base directory" in build settings to `/`:

<img width="929" alt="Screen Shot 2022-08-17 at 8 23 39 PM" src="https://user-images.githubusercontent.com/605361/185260578-d4634c9f-fd66-4c31-b079-d8ba5f82c605.png">

**Comment by SteelWagstaff** [comment]
Done -- build was successful last night. Happy to do something similar for Aetna when needed as well. Is it ready for that now?

**Comment by greatislander** [comment]
It isn't yet.

**Comment by SteelWagstaff** [comment]
@greatislander docs title link uses wrong version (1.7.1 when should be 1.7.2). any idea why?
<img width="903" alt="Screen Shot 2022-08-18 at 7 55 31 AM" src="https://user-images.githubusercontent.com/13485451/185412945-b9dfd32a-2f8f-429e-ac01-7d19cf40e642.png">

**Comment by greatislander** [comment]
I hadn't merged `dev` into `main` and `main` is where it deploys from.
