### ISSUE TITLE
.textbox--sidebar does not use defined variable $textbox-sidebar-max-width

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/buckram#327]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

If this is incorrect, please forgive. I'm trying to create a custom child theme and teach myself SCSS and buckram at the same time.

Buckram has a defined variable $textbox-sidebar-max-width: 25% !default;
https://buckram.pressbooks.org/#variable-textbox-sidebar-max-width

However, in buckram/assets/styles/components/specials/_textboxes.scss the max-width value is hardcoded at 25%.

![Screenshot 2023-06-17 at 7 39 40 PM](https://github.com/pressbooks/pressbooks/assets/29982981/1cfc8916-c278-44e8-ab60-a6f7bf5fbc28)

**Comment by beckej13820** [comment]
Thanks Steel, I've made those two changes.

Is that a Pressbooks naming convention or an everybody-in-the-world naming convention?

**Comment by greatislander** [comment]
@beckej13820: it's based on this if I'm not mistaken: https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by SteelWagstaff** [comment]
@beckej13820 yes, Ned is correct. We've recently started enforcing those Conventional Commits conventions on branches and PR titles/commits -- once we're doing this consistently it will allow us to automate (and improve the speed and accuracy of) our release notes for various projects.
