### ISSUE TITLE
Add variables for TOC section title

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/buckram#69]

**Comment by greatislander** [comment]
??

**Comment by dannylonglegs** [comment]
The header for the TOC front matter section is often targeted separately in old book themes from other front matter section titles. It needs its own variables.

**Comment by greatislander** [comment]
Oh, got it.

**Comment by greatislander** [comment]
Already there:

- [component](https://github.com/pressbooks/buckram/blob/dev/assets/styles/components/section-titles/_front-matter.scss#L75-L86)
- [variables](https://github.com/pressbooks/buckram/blob/dev/assets/styles/variables/_section-titles.scss#L638-L690)
