### ISSUE TITLE
Chapter Author Variables

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/buckram#78]
### Variables to Add:
- [ ] Margin Top
- [ ] Margin Bottom

**Comment by greatislander** [comment]
Already covered by:

- [`$section-title-author-spacing`](https://buckram.pressbooks.org/#section-titles-variable-section-title-author-spacing) (for author that follows title)
- [`section-subtitle-author-spacing`](https://buckram.pressbooks.org/#section-titles-variable-section-subtitle-author-spacing) (for author that follows subtitle)
- [`section-author-margin-bottom`](https://buckram.pressbooks.org/#section-titles-variable-section-author-margin-bottom)
