### ISSUE TITLE
Page break before chapter subtitle 

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/buckram#81]
When a subtitle (by itself with no other chapter features) is used on a chapter, the page breaks before the subtitle and the subtitle is pushed to the next page.

**Comment by greatislander** [comment]
Is there a title on the chapter as well? Or just subtitle?

**Comment by dannylonglegs** [comment]
There is a title as well

**Comment by greatislander** [comment]
Fixed in https://github.com/pressbooks/buckram/commit/1dc9c268979d94db1cf24759411fa049501c6dac.
